create table city
(
    id       int8 generated by default as identity,
    name     varchar(60) not null,
    state_id int8         not null,
    primary key (id)
);
create table form_of_payment
(
    id          int8 generated by default as identity,
    description varchar(60) not null,
    primary key (id)
);
create table "group"
(
    id   int8 generated by default as identity,
    nome varchar(60) not null,
    primary key (id)
);
create table group_permission
(
    group_id      int8 not null,
    permission_id int8 not null
);
create table item_ordered
(
    id          int8 generated by default as identity,
    observation varchar(100),
    quantity    int4 not null,
    total_price numeric(19, 2),
    unit_price  numeric(19, 2),
    "order_id"  int8 not null,
    product_id  int8 not null,
    primary key (id)
);
create table kitchen
(
    id   int8 generated by default as identity,
    name varchar(60) not null,
    primary key (id)
);
create table "order"
(
    id                   int8 generated by default as identity,
    address_cep          varchar(10),
    address_complement   varchar(100),
    address_district     varchar(60),
    address_number       varchar(10),
    address_public_place varchar(60),
    cacelation_at        timestamp,
    confirmation_at      timestamp,
    created_at           timestamp not null,
    delivery_at          timestamp,
    order_status         int4,
    shipping_rate        numeric(19, 2),
    sub_total            numeric(19, 2),
    total_value          numeric(19, 2),
    address_city_id      int8,
    "client_id"          int8      not null,
    form_of_payment_id   int8      not null,
    restaurant_id        int8      not null,
    primary key (id)
);
create table "order_items"
(
    order_id int8 not null,
    items_id int8 not null
);
create table permission
(
    id          int8 generated by default as identity,
    description varchar(100) not null,
    name        varchar(60) not null,
    primary key (id)
);
create table product
(
    id            int8 generated by default as identity,
    active        boolean        not null,
    description   varchar(100)   not null,
    name          varchar(60)   not null,
    price         numeric(19, 2) not null,
    restaurant_id int8           not null,
    primary key (id)
);
create table restaurant
(
    id                   int8 generated by default as identity,
    address_cep          varchar(10),
    address_complement   varchar(100),
    address_district     varchar(60),
    address_number       varchar(10),
    address_public_place varchar(60),
    created_at           timestamp,
    is_open              boolean        not null,
    name                 varchar(60)   not null,
    shipping_rate        numeric(19, 2) not null,
    updated_at           timestamp,
    address_city_id      int8,
    kitchen_id           int8           not null,
    primary key (id)
);
create table restaurant_form_payment
(
    restaurant_id   int8 not null,
    form_payment_id int8 not null
);
create table state
(
    id   int8 generated by default as identity,
    name varchar(60) not null,
    uf   varchar(4) not null,
    primary key (id)
);
create table "user"
(
    id         int8 generated by default as identity,
    created_at timestamp,
    email      varchar(60) not null,
    name       varchar(60) not null,
    password   varchar(60) not null,
    primary key (id)
);
create table user_group
(
    user_id  int8 not null,
    group_id int8 not null
);
alter table if exists order_items
    add constraint UK_d0vxbj4gqklaa3ro4kja2h72x unique (items_id);
alter table if exists city
    add constraint FK6p2u50v8fg2y0js6djc6xanit foreign key (state_id) references state;
alter table if exists group_permission
    add constraint FKss14p30qbokhpkpdov4ha3wro foreign key (permission_id) references permission;
alter table if exists group_permission
    add constraint FKdw7bnraty6qo3mdq6phatbglg foreign key (group_id) references "group";
alter table if exists item_ordered
    add constraint FKnh9qq6i8ucmk33h38ixbyh1r5 foreign key ("order_id") references "order";
alter table if exists item_ordered
    add constraint FKjeccc4yadljqa9tnbmkqu4om7 foreign key (product_id) references product;
alter table if exists "order"
    add constraint FKn2pr35270ywf5wd1qcltye8mr foreign key (address_city_id) references city;
alter table if exists "order"
    add constraint FKmkjorvpnpc04qy9pln8o3pk87 foreign key ("client_id") references "user";
alter table if exists "order"
    add constraint FKcs29cmeyredpp9qaf9dhh7xig foreign key (form_of_payment_id) references form_of_payment;
alter table if exists "order"
    add constraint FKjdm2akwbbctncy3xae6604lf1 foreign key (restaurant_id) references restaurant;
alter table if exists "order_items"
    add constraint FKgylvs0m394by6vb2j77ykl7qx foreign key (items_id) references item_ordered;
alter table if exists "order_items"
    add constraint FK4yw445vtxvh73ntmo87t4hraj foreign key (order_id) references "order";
alter table if exists product
    add constraint FKp4b7e36gck7975p51raud8juk foreign key (restaurant_id) references restaurant;
alter table if exists restaurant
    add constraint FK8pcwgn41lfg43d8u82ewn3cn foreign key (address_city_id) references city;
alter table if exists restaurant
    add constraint FKrur1dqx79jim8s8dvdp16qc3d foreign key (kitchen_id) references kitchen;
alter table if exists restaurant_form_payment
    add constraint FKsheftkvya0hkfx4lsg50h79ih foreign key (form_payment_id) references form_of_payment;
alter table if exists restaurant_form_payment
    add constraint FK7b8eis4ak2l7j8ra4yt1qef3o foreign key (restaurant_id) references restaurant;
alter table if exists user_group
    add constraint FK71ue7uuqo0neoodkx7smf7e3o foreign key (group_id) references "group";
alter table if exists user_group
    add constraint FK1vm7hjlu1n79o7y4ga4091dj6 foreign key (user_id) references "user";
